### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by ahmadawais** [pixel2/Google-did-you-mean#1]
It doesn't output anything on the search page. Care to demonstrate an example?
Is it possible your AJAX url is wrong?

**Comment by pixel2** [comment]
Hi @ahmadawais, Sorry but this repository isn't being maintained anymore and google have most likely changed there code.

**Comment by ahmadawais** [comment]
@pixel2 Any suggestions then?

**Comment by pixel2** [comment]
Sorry, I don't have any suggestions.

tisdag 1 mars 2016 skrev Ahmad Awais notifications@github.com:

**Comment by ahmadawais** [comment]
Thanks, anyway :)
